name: Error
description: Error en la web
title: "Error: "
labels: ["error"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: 
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: v-node
    attributes:
      label: ¿Que version de Node.js estás usando?
      multiple: false
      options:
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - Otra
    validations:
  - type: dropdown
    id: browsers
    attributes:
      label: ¿Es un error en la web?
      multiple: false
      options:
        - Si
        - No
